### ISSUE TITLE
Should read the result of executed shell command, not the global $?

### ISSUE THREAD

**Issue by ssmiech** [ssmiech/rubotium#19]
```ruby
rubotium-0.0.17/lib/rubotium/apk/android_apk.rb:29:in `results': undefined method `exitstatus' for nil:NilClass (NoMethodError)
00:00:38.014 	from /usr/local/lib/ruby/gems/2.0.0/gems/rubotium-0.0.17/lib/rubotium/apk/android_apk.rb:37:in `parsed_aapt'
00:00:38.014 	from /usr/local/lib/ruby/gems/2.0.0/gems/rubotium-0.0.17/lib/rubotium/apk/android_apk.rb:17:in `package_name'
00:00:38.014 	from /usr/local/lib/ruby/gems/2.0.0/gems/rubotium-0.0.17/lib/rubotium/package.rb:13:in `name'
00:00:38.014 	from /usr/local/lib/ruby/gems/2.0.0/gems/rubotium-0.0.17/lib/rubotium.rb:63:in `block in new'
00:00:38.014 	from /usr/local/lib/ruby/gems/2.0.0/gems/parallel-0.9.2/lib/parallel.rb:389:in `call'
00:00:38.014 	from /usr/local/lib/ruby/gems/2.0.0/gems/parallel-0.9.2/lib/parallel.rb:389:in `call_with_index'
00:00:38.014 	from /usr/local/lib/ruby/gems/2.0.0/gems/parallel-0.9.2/lib/parallel.rb:229:in `block (3 levels) in work_in_threads'
00:00:38.014 	from /usr/local/lib/ruby/gems/2.0.0/gems/parallel-0.9.2/lib/parallel.rb:397:in `with_instrumentation'
00:00:38.014 	from /usr/local/lib/ruby/gems/2.0.0/gems/parallel-0.9.2/lib/parallel.rb:227:in `block (2 levels) in work_in_threads'
00:00:38.014 	from /usr/local/lib/ruby/gems/2.0.0/gems/parallel-0.9.2/lib/parallel.rb:221:in `loop'
00:00:38.014 	from /usr/local/lib/ruby/gems/2.0.0/gems/parallel-0.9.2/lib/parallel.rb:221:in `block in work_in_threads'
00:00:38.014 	from /usr/local/lib/ruby/gems/2.0.0/gems/parallel-0.9.2/lib/parallel.rb:65:in `block (2 levels) in in_threads'
```

**Comment by ssmiech** [comment]
Fixed here: 6456cea4cd26669e7ca3e5ac01061b7473df3404
